//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer_Marketplace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bid
    {
        public int bid_id { get; set; }
        public int project_id { get; set; }
        public int freelancer_id { get; set; }
        public decimal bid_amount { get; set; }
        public string proposal_text { get; set; }
        public Nullable<bool> isapproved { get; set; }
        public Nullable<System.DateTime> bidstime { get; set; }
    
        public virtual usersdata usersdata { get; set; }
        public virtual project project { get; set; }
    }
}
