//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer_Marketplace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar_events
    {
        public int event_id { get; set; }
        public int userid { get; set; }
        public string event_title { get; set; }
        public string event_description { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
    
        public virtual usersdata usersdata { get; set; }
        public virtual usersdata usersdata1 { get; set; }
        public virtual usersdata usersdata2 { get; set; }
        public virtual usersdata usersdata3 { get; set; }
    }
}
