//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer_Marketplace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.bids = new HashSet<bid>();
            this.takenprojects = new HashSet<takenproject>();
            this.uploadedprojects = new HashSet<uploadedproject>();
        }
    
        public int project_id { get; set; }
        public int client_id { get; set; }
        public string title { get; set; }
        public string brand_name { get; set; }
        public string project_description { get; set; }
        public Nullable<decimal> budget { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public string project_status { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bid> bids { get; set; }
        public virtual usersdata usersdata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<takenproject> takenprojects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uploadedproject> uploadedprojects { get; set; }
    }
}
