//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer_Marketplace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class reported_issues
    {
        public int report_id { get; set; }
        public int reporter_id { get; set; }
        public int reported_user_id { get; set; }
        public string report_content { get; set; }
        public string report_status { get; set; }
        public byte[] reported_time { get; set; }
    
        public virtual usersdata usersdata { get; set; }
        public virtual usersdata usersdata1 { get; set; }
        public virtual usersdata usersdata2 { get; set; }
        public virtual usersdata usersdata3 { get; set; }
        public virtual usersdata usersdata4 { get; set; }
        public virtual usersdata usersdata5 { get; set; }
        public virtual usersdata usersdata6 { get; set; }
        public virtual usersdata usersdata7 { get; set; }
    }
}
