//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer_Marketplace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews_ratings
    {
        public int review_id { get; set; }
        public int reviewed_user_id { get; set; }
        public int reviewer_id { get; set; }
        public Nullable<int> rating_score { get; set; }
    
        public virtual usersdata usersdata { get; set; }
        public virtual usersdata usersdata1 { get; set; }
        public virtual usersdata usersdata2 { get; set; }
        public virtual usersdata usersdata3 { get; set; }
        public virtual usersdata usersdata4 { get; set; }
        public virtual usersdata usersdata5 { get; set; }
        public virtual usersdata usersdata6 { get; set; }
        public virtual usersdata usersdata7 { get; set; }
    }
}
