//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer_Marketplace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadedproject
    {
        public int files_id { get; set; }
        public int project_id { get; set; }
        public int freelancer_id { get; set; }
        public string filepath { get; set; }
        public bool isverified { get; set; }
        public System.DateTime uploadtime { get; set; }
        public string formessage { get; set; }
    
        public virtual project project { get; set; }
        public virtual usersdata usersdata { get; set; }
    }
}
